# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SWXWTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'BGFMDB', '~> 2.0.9'
  pod 'SVProgressHUD'
  pod 'YYModel'

  # Pods for SWXWTestProject

  target 'SWXWTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SWXWTestProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
